install.packages("MASS")
library(MASS)
attach(Boston)
?Boston
head(Boston)
dim(Boston)
names(Boston)
str(Boston)
nrow(Boston)
ncol(Boston)
summary(Boston)
summary(Boston$crim)

install.packages("ISLR")
library(ISLR)
data("Auto")
head(Auto)
head(Auto,18)
names(Auto)
summary(Auto)
fivenum(Auto$mpg)
boxplot(Auto$weight)
mean(Auto$weight)
median(Auto$weight)
help("read.csv")

data1<-read.csv(file.choose(),header = TRUE)
head(data1)
summary(data1)
boxplot(data1)
fivenum(data1,na.rm = TRUE)
